Stepzen login retry mechanism added

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -17,6 +17,14 @@ inputs:
   adminkey:
     description: "Admin key of the StepZen account"
     required: true
+  retries:
+    description: "Number of retry attempts."
+    required: false
+    default: "3"
+  retryWaitSeconds:
+    description: "Time to wait between retries in seconds."
+    required: false
+    default: "10"
 
 outputs:
   domain:
@@ -40,7 +48,20 @@ runs:
         echo "::add-mask::${adminkey}"
     - name: "login"
       run: |
-        stepzen login ${{ inputs.domain }} --account ${{ inputs.account }} --adminkey ${{ inputs.adminkey }}
+        retries=${{ inputs.retries }}
+        retry_wait=${{ inputs.retryWaitSeconds }}
+
+        count=0
+        until [ $count -ge $retries ]
+        do
+          stepzen login ${{ inputs.domain }} --account ${{ inputs.account }} --adminkey ${{ inputs.adminkey }} && break
+          count=$((count+1))
+          sleep $retry_wait
+        done
+        if [ $count -ge $retries ]; then
+          echo "Stepzen login failed after $retries attempts."
+          exit 1
+        fi        
       shell: bash
     - id: output
       run: |
